name: shell-branch-name
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Current branch name
        run: |
          echo $(git branch | grep \* | cut -d ' ' -f2)
