name: shell-branch-name
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Branch name
        run: |
          if [[ ${{ github.event_name }} == "push" ]]
          then
            echo Branch ${GITHUB_REF##*/}
          elif [[ ${{ github.event_name }} == "pull_request" ]]
          then
            echo Branch ${{ github.event.pull_request.base.ref }}
          fi
