name: shell-branch-name
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Running on the default branch.
        if: ${{ github.event_name == 'push' }}
        run: |
          echo Branch ${GITHUB_REF##*/}
        # Outputs: "Running on default: main".
      
      - name: Running on a pull request branch.
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo Branch ${{ github.event.pull_request.base.ref }}
          
          
#       - name: Current branch name
#         run: echo ${{ github.event.pull_request.base.ref }}
#       - name: Current branch name
#         run: |
#           echo $(git branch --show-current)
