name: shell-branch-name
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
        
      - name: Current branch name
        run: |
          echo $(git rev-parse --abbrev-ref HEAD)
