name: shell-branch-name
on:
  [push, pull_request]:
    branches:
      - 'main'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Current branch name
        run: |
          echo $(shell git branch | grep \* | cut -d ' ' -f2)
