name: shell-branch-name
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
        
      - name: Running on the default branch.
        if: ${{ github.event.pull_request.base.ref }} == ''
        run: |
          echo Branch ${GITHUB_REF##*/}
        # Outputs: "Running on default: main".
      
      - name: Running on a pull request branch.
        if: ${{ github.event.pull_request.base.ref }} != ''
        run: |
          echo Branch ${{ github.event.pull_request.base.ref }}
        # Outputs: "Running on pr: feature/test".
        
#       - name: Current branch name
#         run: echo On branch ${GITHUB_REF##*/}

#       - name: Current branch name
#         run: |
#           echo $(git branch --show-current)
